export const UserActionTypes = {
    SET_USER_DETAILS: "SET_USER_DETAILS",
    SET_LOGIN_STATUS: "SET_LOGIN_STATUS",
    SET_USER_POST: "SET_USER_POST",
    SET_REQUESTED_USER: "SET_REQUESTED_USER",
    GET_USER_DETAILS: "GET_USER_DETAILS",
    GET_LOGIN_STATUS: "GET_LOGIN_STATUS",
    GET_USER_POST: "GET_USER_POST",
    GET_REQUESTED_USER: "GET_REQUESTED_USER",
    UPDATE_REQUESTED_USER_TRUE: "UPDATE_REQUESTED_USER_TRUE",
    UPDATE_REQUESTED_USER_FALSE: "UPDATE_REQUESTED_USER_FALSE"

}